# Generated by Django 2.0 on 2022-05-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptionistV', '0002_remove_r_detail_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='R_Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, null=True)),
                ('Token', models.CharField(max_length=30, null=True)),
                ('Generated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceptionistV.R_Detail')),
            ],
        ),
    ]
