# Generated by Django 2.0 on 2022-05-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptionistV', '0003_r_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_detail',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
