# Generated by Django 2.0 on 2022-05-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorV', '0002_remove_d_detail_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_detail',
            name='Appointment_fees',
            field=models.IntegerField(null=True),
        ),
    ]
