# Generated by Django 2.0 on 2022-05-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorV', '0005_d_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_detail',
            name='Display_Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
