# Generated by Django 2.0 on 2022-05-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorV', '0006_d_detail_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_detail',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
