# Generated by Django 2.0 on 2022-05-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_detail',
            name='Registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='p_detail',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
