# Generated by Django 2.0 on 2022-05-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0003_auto_20220522_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_appointment',
            old_name='Registered_at',
            new_name='Appointment_reg_at',
        ),
        migrations.RemoveField(
            model_name='p_appointment',
            name='modified_at',
        ),
    ]
