# Generated by Django 2.0 on 2022-05-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0005_p_appointment_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_appointment',
            name='Payment_Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
