# Generated by Django 2.0 on 2022-05-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0006_auto_20220522_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_appointment',
            name='App_Rej_Reason',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='p_appointment',
            name='Prescription',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
