# Generated by Django 2.0 on 2022-05-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0007_auto_20220524_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_appointment',
            name='App_Rej_Reason',
            field=models.CharField(default='Not Rejected', max_length=50),
        ),
    ]
