# Generated by Django 2.0 on 2022-05-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0010_p_appointment_doctor_visited_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
