# Generated by Django 2.0 on 2022-05-26 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0011_p_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_detail',
            name='Disease',
        ),
    ]
