# Generated by Django 2.0 on 2022-05-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0013_p_appointment_appointment_mod_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_appointment',
            name='Doctor_Visited_Status',
        ),
    ]
