# Generated by Django 2.0 on 2022-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0014_remove_p_appointment_doctor_visited_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_appointment',
            name='Medical_History',
        ),
        migrations.AddField(
            model_name='p_detail',
            name='Medical_History',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
