# Generated by Django 2.0 on 2022-05-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0017_auto_20220530_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_appointment',
            name='Appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='p_detail',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
