# Generated by Django 2.0 on 2022-05-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0018_auto_20220531_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_appointment',
            name='Patient_Age',
        ),
        migrations.AddField(
            model_name='p_detail',
            name='Patient_Age',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
