# Generated by Django 2.0 on 2022-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientV', '0020_p_detail_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_security',
            name='OTP',
            field=models.IntegerField(null=True),
        ),
    ]
